# Generated by Django 5.0 on 2024-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadVideo', '0003_usermediafetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='primaryAudio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermediafetch',
            name='primaryAudio',
            field=models.TextField(null=True),
        ),
    ]
