# Generated by Django 5.0 on 2024-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadVideo', '0004_usermedia_primaryaudio_usermediafetch_primaryaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(null=True, upload_to='user_audio/'),
        ),
    ]
