# Generated by Django 5.0 on 2024-01-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadVideo', '0005_video_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='primaryAudio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadVideo.video'),
        ),
        migrations.AlterField(
            model_name='usermediafetch',
            name='primaryAudio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadVideo.video'),
        ),
    ]
