# Generated by Django 5.0 on 2024-01-17 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadVideo', '0012_usermedia_thumbnail_usermediafetch_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at date'),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated date at'),
        ),
    ]
