# Generated by Django 5.0 on 2023-12-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
