# Generated by Django 5.0 on 2024-01-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_uservideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
